/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class solver_SokoBot */

#ifndef _Included_solver_SokoBot
#define _Included_solver_SokoBot
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     solver_SokoBot
 * Method:    solver
 * Signature: (II[[C[[C)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_solver_SokoBot_solver
  (JNIEnv *, jobject, jint, jint, jobjectArray, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
